### ISSUE TITLE
0.17.0: `throws` clause with an unresolved type panics the compiler (index out of bounds, type_ref.rs:346, exit 134) — 0.16.0 gives a clean E0002

### ISSUE THREAD

**Issue by BenSpex** [BoundaryML/baml#4587]
## Summary

On **0.17.0**, a `throws` clause naming a type that does not resolve **panics the compiler** (index-out-of-bounds in `baml_compiler2_hir/src/type_ref.rs:346`, SIGABRT / exit 134) instead of reporting `E0002: unresolved type`. 0.16.0 reports the clean E0002 for the same file, so this looks like a 0.17 regression.

Found while probing #4370's suggested workaround (narrowing the throws contract) during a real project's 0.15→0.17 migration.

## Reproduce (six lines, `baml check` is enough — no generator section needed)

`baml_src/main.baml`:

```baml
client C = openai.GenericClient.new(model = "m", base_url = env.BASE_URL, api_key = env.API_KEY);

function Hello(name: string) -> string throws ai.errors.LlmClient {
    client: C
    prompt: `${role("user")}Say hello to ${name}.`
}
```

```console
$ BAML_VERSION=0.17.0 baml check --from .
thread '<unnamed>' (3537872) panicked at crates/baml_compiler2_hir/src/type_ref.rs:346:19:
index out of bounds: the len is 1 but the index is 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ echo $?
134
```

`ai.errors.LlmClient` is not a real 0.17 stdlib name (the class is `baml.errors.LlmClient`) — but a wrong type name in a `throws` clause should be a diagnostic, not a SIGABRT.

0.16.0 on the same file:

```console
$ BAML_VERSION=0.16.0 baml check --from .
error[E0002]: unresolved type: ai.errors.LlmClient
```

(alongside an unrelated `GenericClient` resolution error on 0.16, since the native-client surface only exists on 0.17 — the E0002 is the relevant diagnostic).

## Why a real consumer hits this

Anyone following #4370's narrowing suggestion is, by definition, experimenting with `throws` type names on a prompt function — a typo'd or wrong-namespace name is the most likely first attempt, and it takes down the compiler instead of pointing at the name. (The narrowing itself also does not work on 0.17.0 — every resolvable candidate is rejected by E0096 with an ever-widening inferred set; that evidence is recorded on #4370 directly, since it belongs to that issue.)

## Versions

| | |
|---|---|
| panics | `0.17.0` stable (latest stable as of 2026-08-25) |
| clean E0002 | `0.16.0` |
| platform | Linux x86_64, `baml wrapper 0.2.0`, versions via `BAML_VERSION` selector |

**Comment by BenSpex** [comment]
**FIXED on `0.17.1-nightly.20260824.b`**: the same six-line repro now reports a clean `main.baml:3:47-3:66 error[E0002]: unresolved type: ai.errors.LlmClient` instead of the `type_ref.rs:346` index-out-of-bounds panic. Re-confirmed the panic on 0.17.0 stable in the same harness immediately before. Will this ride a 0.17.x stable?
